masschallenge/django-accelerator

- .travis.yml
- Makefile
- accelerator/models/__init__.py
- accelerator/test_runner.py
**Changes Introduced in [AC-4819](https://masschallenge.atlassian.net/browse/AC-4819):**
- add travis.yml file for django-accelerator.
- adjust makefile such that `make code-check` works correctly in travis.
**Test:**
- Introduce a failing test, push it. See that travis is failing on PR and PUSH.
- Fix that test, introduce a style failure, push it. See that travis is failing in PR but passing in PUSH.
- Fix that style failure, push it. See that travis succeeds.
- Locally, `make code-check` is working as expected.
**Note:**
- Each commit triggers 4 builds - twice for each of [PR, PUSH], one for Python 2.7 and one for 3.6.
- There's a known bug in the travis log output, as described in [AC-4869](https://masschallenge.atlassian.net/browse/AC-4869). I'd love this to be reviewed as part of …
> [AC-4819] - Set up Travis for django-accelerator

- setup.py
Builds of django-accelerator `development` on Python 2.7  currently failThis problem arose because at the time we specified `Django>=1.8` as a requirement, the highest release of Django was less than 2.0. **Then 2.0 was released!**
The development branch hasn't had a Travis build in a month, that's how we missed this.
**TO TEST**
* Confirm that [Travis build for this branch](https://travis-ci.org/masschallenge/django-accelerator/builds/315007712) does not fail; the [Python 2.7 build on the development branch](https://travis-ci.org/masschallenge/django-accelerator/builds/298783595) does.
> [AC-5175] pin django-accelerate's Django version below 2.0

- accelerator_abstract/models/accelerator_model.py
Given the urgency of this bug, I'm posting this PR even though we don't have a test yet. Existing tests all pass. At a minimum we should try running this code with the prod data on staging. Click on ticket number in heading above for more details.
My my grep/count, there are 14 models in `accelerator_abstract` that neither override the `__str__` method nor have a `name` field. These are the ones that will fall back to this parent method and benefit from this fix.
* base_startup_cycle_interest.py
* label_model.py
* base_category_header_page.py
* base_user_role_menu.py
* base_startup_attribute.py
* base_expert_profile.py
* base_member_profile.py
* base_paypal_refund.py
* base_site_redirect_page.py
* base_paypal_payment.py
* base_file_page.py
* base_entrepreneur_profile.py
* …
> [AC-5478] fix __str__ call causing bottomless recursion

- Makefile
- Explicitly use python3.6 when running `make migrations`
- Add check and useful error message if python3.6 isn't installed
Background:
It was discovered that as much as the Makefile was pointing to `python3`, it may not be pointing to the correct version of python3 i.e. v3.6. Hence the change and extra check.
> [AC-5894] Explicitly use python3.6 in Makefile

- accelerator/apps.py
- accelerator_abstract/apps.py
**Changes Introduced in [AC-5896](https://masschallenge.atlassian.net/browse/AC-5896):**
- add get_profile to user class on accelerator app as well.
**Test:**
- in impact-api, run `make django-shell`
run:
```
from accelerator.models import StartupMentorRelationship
StartupMentorRelationship.objects.first()
```
- on django-accelerator's development this fails, and succeeds on branch
> [AC-5896] - Bug - Make sure `get_profile()` is available on impact-api

- accelerator/tests/factories/factory_utils.py
- simpleuser/tests/factories/user_factory.py
Converting the `datetime` to a `date` strips tz info, causing a naive datetime to be created incorrectly.  
Came across this while working on a test for AC-5836, so fixed it. 
To test: 
check out impact-api, run tests. Note timezone warning
point impact-api at this branch, build, and run tests again. Note, no timezone warning
> [AC-5898] Eliminate naive datetime

- Makefile
Testing instructions: try to find something that this breaks.
Also see the [accelerate PR](https://github.com/masschallenge/accelerate/pull/2023).
> [AC-6320] Upgrade to Django 1.11.18 on accelerate and django-accelerator

- accelerator/tests/contexts/judge_feedback_context.py
- accelerator/tests/factories/judge_application_feedback_factory.py
add unique together constraint to judge_application_feedback_factory and allow us change application feedback from judge_feedback_context
- These changes are introduced to support a test in the [sibling PR](https://github.com/masschallenge/accelerate/pull/2064) on accelerate
- This PR should be merged first as it has dependent tests
- This does not need to be merged in any particular order relative to other django-accelerator PRs since it does not introduce a migration
> AC-6272: Update Judge Progress Stats for New Allocator

- accelerator/tests/contexts/startup_team_member_context.py
- Add startup role as an argument to the StartupTeamMemberContext
-Run `make test tests="mc_apply.tests.test_startup_dashboard_view"` in the accelerate development branch while checked out to this branch in django-accelerator
> add startup role to startupteammember context

- accelerator/models/__init__.py
- accelerator_abstract/models/__init__.py
- accelerator_abstract/models/base_mentor_program_office_hour.py
**Changes Introduced in [AC-6540](https://masschallenge.atlassian.net/browse/AC-6540):**
- Made the location field in the office hour creation mandatory
- Removed old locations and added new ones
**Test:**
_checkout this branch on both Accelerate and Django Accelerator Repos_
- Visit the Office Hours page and try to create a new Office Hour
- Notice that none of the valid locations is selected by default, submit without changing and see an alert
- Notice also that locations were added and removed as specified in the ticket.
NB: Sibling PR: https://github.com/masschallenge/accelerate/pull/2119
> [AC-6540] Office Hours - Require location and add a default

- .gitignore
- accelerator/tests/contexts/startup_team_member_context.py
- accelerator/tests/test_core_profile.py
- accelerator/tests/test_startup.py
- accelerator/tests/test_user_role.py
- accelerator/tests/utils.py
- accelerator_abstract/models/base_core_profile.py
- accelerator_abstract/models/base_permission_checks.py
- accelerator_abstract/models/base_startup.py
- accelerator_abstract/models/base_user_role.py
- accelerator_abstract/models/base_utils.py
- accelerator_abstract/tests/test_base_permissions_checks.py
- accelerator_abstract/tests/test_base_user_utils.py
- accelerator_abstract/tests/test_base_utils.py
- simpleuser/models.py
- simpleuser/tests/test_models.py
- move logic from accelerate into here to allow algolia to reindex automatically when a User object is saved
this is deployed on test2
- visit test2 and log in as staff
- now visit https://test2.masschallenge.org/people/ and behold the new people directory
if local testing is your thing
- checkout this branch on the directory and impact
- ensure to be logged in on accelerate
- visit localhost:1234/people and behold the new people directory
- there are 3 related PRs ([accelerate](https://github.com/masschallenge/accelerate/pull/2117), [directory](https://github.com/masschallenge/directory/pull/136), [impact](https://github.com/masschallenge/impact-api/pull/275)). The accelerator PR should be merged in first, then the order of the merge is not important but it's important that a deploy is …
> AC-6377: Build new people directory page in front-end repo (React + SUI)

- accelerator/migrations/0009_create_initial_criteria.py
- ensure migration 009 does not attempt to create criteria for a judging round that does not exist
- be on development in django-accelerator
- on impact, run `make db-shell` and while there run `create database mc_dev_1;`
- in the `.dev.env` change `mc_dev` to `mc_dev_1` on L5
- then run `make migrate`, note the migration failure
- now checkout AC-6373 on django-accelerator
- and run `make migrate` again, note that the migrations now run to completion with no error
When creating stacks on AWS, migrations initially run on an empty database and a failing migration stops the impact server from being accessible. This allows the whole stack be accessible when it's initially created
Make sure your `.dev.env` file is reverted back to it's original state to avoid bugs.
> AC-6373: Migration 0009_create_initial_criteria should not fail on an empty database

- accelerator/managers/member_profile_manager.py
- accelerator/managers/profile_manager.py
- accelerator/tests/factories/base_profile_factory.py
- accelerator/tests/factories/member_profile_factory.py
- override create method on objects manager to delete existing profile before creating another
On local
- on accelerate open the `mcproject/settings.py` file and fill in the fields below
```
ALGOLIA = {
'APPLICATION_ID': '', # get this from your impact-api .env file i.e. ALGOLIA_APPLICATION_ID
'API_KEY': '', # get this from your impact-api .env file i.e. ALGOLIA_API_KEY
'INDEX_PREFIX': 'dev'
}
ALGOLIA_ENABLED = True
```
- while on development on all branches
- go to http://localhost:8181/accounts/register/entrepreneur/ and create an entrepreneur, see the failure with a duplicate user error
- checkout AC-6622 on accelerate and accelerator
- go to http://localhost:8181/accounts/register/entrepreneur/ and create an entrepreneur, see that it works
This is also deployed on test2 for further QA …
> AC-6622: AC-6622: Internal Server Error on /startup/000/team/add and /accounts/register/entrepreneur/

- Makefile
- git-hooks/pre-commit
- git-hooks/prepare-commit-msg
- add precommit git hooks
- checkout this branch
- run `make clean`. to delete the venv
- run `make code-check`. this simulates a situation where django-accelerator will rebuild it's virtualenv and in the process set up the git hook
- once this is done, add `import pdb; pdb.set_trace()` in a file and stage the file i.e. `git add <file-you-added-pdb-to>` and attempt to commit the file. Note that the commit is blocked as it would be on impact/ accelerate.
- Now make a random, legal change and commit it. Note that the branch name is appended to the commit message like it is on accelerate/ impact
> AC-5610: Add issue-number in commit message git-hook to django-accelerator

- accelerator/managers/member_profile_manager.py
- accelerator/managers/profile_manager.py
- settings.py
- make verbose logs info level rather than warning
- disable info logging
- while on development
- run `make test` in django-accelerator and notice the logging that drowns out basically everything
- now checkout AC-6715
- run `make test` again and see our tests are back to cleanliness 🏆
> AC-6715: Silence logging when running tests on impact-api

- setup.py
**Changes Introduced in [AC-6714](https://masschallenge.atlassian.net/browse/AC-6714):**
- Locked django-mptt to 0.9.0
**Test:**
_On development_
- `make clean`
- `make venv`
- `make migrations`
- Notice a migration is created
_checkout this branch_
- Delete migration from previous steps and do the same on this branch and notice no migration is created.
> [AC-6714] Unexpected Change on Mptt Models	

- accelerator/migrations/0054_add_eventbrite_organizer_id_field.py
- accelerator/migrations/0054_update_eventbrite_organizer_id_field.py
- accelerator_abstract/models/base_program.py
- Rename feild eventbrite_organization_id to eventbrite_organizer_id
- Checkout this branch and run `make migrate` in accelerate
- Follow [this link](http://localhost:8181/admin/mc/program/23/change/)
- Notice that the eventbrite_organization_id field has changed to eventbrite_organizer_id
> Rename eventbrite_organization_id field to eventbrite_organizer_id

- .travis.yml
ensure AC-6678 branch does not lead to auto-deployment
- A passing travis build and code change review should be enough to call this done.
- this is a cleanup task from the [AC-6678](https://masschallenge.atlassian.net/browse/AC-6678) ticket
> AC-6754: Prevent the AC-6684 branch from automatically deploying to pre-staging

- accelerator_abstract/models/base_user_role.py
- Modify the `has_user_role_base` function to checks if a user is a finalist in a program that has either active or has ended
- Follow the test instructions on the ``accelerate` [repo](https://github.com/masschallenge/accelerate/pull/2204)
> AC-6775  Mentors and Goals unavailable after Program Ends

- .travis.yml
- allow auto-deploy when branches are merged to development from a pr
Unfortunately this is one of those wait-and-see tickets. However I tested a few edge cases.
Note that in my examples below 
- `AC-6810` was acting as the dummy development branch
- to verify if an autodeply was **not** triggered, looking at the build log and seeing that the last command triggered took less than a second shows nothing happened.
> if a pr is raised from development to some other branch, is an auto-deploy triggered?
Nope, here's the [build](https://travis-ci.org/masschallenge/django-accelerator/builds/549654050) covering that. 
> if a pr is raised against development, is the deployed triggered then?
Nope, here's the [build](https://travis-ci.org/masschallenge/django-accelerator/builds/549168346) for that …
> AC-6810: Correct logic in travis config to allow auto-deploy to pre-staging

- accelerator/tests/contexts/startup_team_member_context.py
- accelerator/tests/test_startup.py
- accelerator_abstract/models/base_startup.py
- add property functions for use in the new startup directory Algolia index and test them
- login as a staff user, our `+superuser` accounts should do for this
- visit https://test6.masschallenge.org/startups and see the new startup directory
- There's a [line of code](https://github.com/masschallenge/django-accelerator/compare/development...AC-1#diff-b2f73bff9028b67f86a2b67c1114048fR214) not covered by tests, ideas about how to test this are too welcome because I haven't found a way yet
- this PR can be merged as is i.e. it has no travis dependencies
> AC-1: Create an Algolia based Startup Directory on Accelerate for staff

- accelerator_abstract/models/base_core_profile.py
https://masschallenge.atlassian.net/browse/AC-6800
Note: unusually, the fix for this is on django-accelerator and the test is on accelerate. Should be obvious why once you look at both. 
Sibling PR: https://github.com/masschallenge/accelerate/pull/2223
Testing notes:
You'll need to find or construct a user with:
- mentor program role grant and judge program role grant in the same program
- no program role grants in programs ending after that program
`40355-user@example.com` is one such user. 
To see the error state, sign in as this user on development. You will be redirected to `/panels` but because the judging round is inactive, you will then be re-redirected to the expert profile page. 
To see the fixed state, check out branch AC-6800 and navigate to http://localhost:8181/ 
This will …
> [AC-6800] Avoid routing to judge pages if not in active judging round

- accelerator/tests/test_core_profile.py
- accelerator_abstract/models/base_core_profile.py
- move 'confirmed_mentor_programs' to the base core profile for Expert, Entrepreneur and Member profiles to use
- deploying to a test machine
- there's a [sibling PR](https://github.com/masschallenge/accelerate/pull/2257) that should be merged **after** this one
> AC-6874: Staff users with Entrepreneur profiles unable to view finalist dashboard pages

- .travis.yml
- use mc admin token for travis build
- a passing travis build should be a good test for this
This PR can be reviewed and merged independently of all it's siblings
> AC-6760: Ensure our automated processes depend on the MassChallenge Machine User

- accelerator_abstract/models/base_core_profile.py
- Move `is_alum` method to CoreProfile model
- A sibling PR is on accelerate
- Reference sibling [PR](https://github.com/masschallenge/accelerate/pull/2263)
> [AC-6876] Side nav does not display on My Startups page

- .travis.yml
- fix travis config to allow continuous deploy to pre-staging
- unfortunately the only way to know if this works, is by actually merging the PR. If this change is successful, an impact-api build will be triggered which will lead to a pre-staging deployment
> AC-6895: Fix a travis config bug preventing continuous deployment to pre-staging

- accelerator/tests/contexts/__init__.py
- accelerator/tests/contexts/user_role_context.py
- accelerator/tests/test_core_profile.py
- accelerator_abstract/models/base_core_profile.py
**Changes introduced in [AC-6873](https://masschallenge.atlassian.net/browse/AC-6873)**
- add confirmed mentor program families to the base core profile, which returns even programs that ended.
**How to test:**
- Check out this branch 
- Masquerade as [user](http://localhost:8181/admin/simpleuser/user/844/masquerade/)
- Notice that they don't have a label on the `Mentor Dashboard` sub nav item despite having participated in previous years.
- Masquerade as [user](http://localhost:8181/admin/simpleuser/user/386/masquerade/)
- Notice that they are two `Mentor Dashboard` sub nav items with labels because they belong to different program families
**How to reproduce:**
- Masquerade as [user](http://localhost:8181/admin/simpleuser/user/844/masquerade/)
- Notice that the user  has a label on the …
> AC-6873 :: Mentors in a single program who have participated in previous years should not see program labels

- .travis.yml
- Makefile
- README.md
To test:
- go to trqvis for this branch and re-trigger a build: https://travis-ci.org/masschallenge/django-accelerator/jobs/563735525#L1259
- see that the coverage report shows up at the bottom of code climate's coverage page: https://codeclimate.com/repos/5d31f01146abc2019e015ec2/settings/test_reporter
> Ac 6909 - integrate code climate coverage reports

- simpleuser/models.py
related PR: https://github.com/masschallenge/accelerate/pull/2309
Context on this - I noticed that a previously passing build for AC-6553 on impact started to fail. Herman confirmed Geofrey that it was due to a superflous line that was added.
> removing insignificant line that breaks tests

- setup.py
This pr removes the max django version constraint of 2.0 from django-accelerator. This is so that we do not have to monkey patch the dockerfile in the django 2 branch as we continue work there. We should be able to safely merge this into development.
> removing max version constraint for django

- .travis.yml
- Makefile
- setup.py
**Testing**: 
* In your local django-accelerator clone on this branch, run `rm -r venv && make test`
* Confirm that Django 2 was in fact used: `. venv/bin/activate && python -c "import django; print(django.VERSION)"`
* Run `tox`, which will run the test suite under both Python 3.6 and Python 3.7.
* Confirm that Django 2 was in fact used: Look for output like `py37 installed:...Django==2.2.8`
> [AC-7033] Update django-accelerator Django version to 2.2

- Makefile
- Bumps up django version
- Travis build with Django 1.11.27 does not fail
local testing
- Follow testing instructions on [accelerate](https://github.com/masschallenge/accelerate/pull/2480)
> [AC-7325] Django Security release, severity "high"

- setup.py
From the ticket: I smoke-tested this by checking out `development` on accelerate, manually editing the django-accelerator code in my container, running `bin/buildout`, and checking that the build was usable (`bin/django` existed; I was able to run tests).
We need this for Django 2, but it's a change being made to the main line (because of how our local build process works), so I wanted confidence that it doesn't break things under Django 1.
> [AC-7340] Fix local build of AC-6999

- .travis.yml
- Dockerfile
- Makefile
- base.Dockerfile
- docker-compose.yml
- scripts/run_make_commands_in_docker.sh
- simpleuser/tests/test_models.py
- Runs django-accelerator in docker
- run `make setup` to setup the docker environment
- run `make run command=<any make command in the Makefile>` like `make run command=test`
- run `make stop-server` to stop the container
- run `make bash-shell` to get into the running container
> AC-7258 Run django-accelerator in a docker environment

- simpleuser/tests/test_models.py
https://masschallenge.atlassian.net/browse/AC-5721
Run tests, see that naive datetime warning goes away on the branch.
> [AC-5721] Eliminate datetime warning on tests

- settings.py
https://masschallenge.atlassian.net/browse/AC-5722
This PR just changes the logging disable level to provide clean output when running tests on django-accelerator. 
Keeping "ERROR" and "CRITICAL" since we should hope we won't see those in tests, and we'd want to know if we were triggering those in the course of day-to-day operations. 
If we add tests that throw those logs, we can revisit that choice. 
To test: run tests. On development, see
```
..........................Missing BaseProfile for user user_13@example.com. Creating.
No CoreProfile Subclass found. Creating a default profile of type 'MEMBER'
.....................................................................................................................................Startup None has no organization
Startup None has no …
```
> [AC-5722] Change log level for tests to eliminate warning output (Lab Day PR)

- accelerator_abstract/models/accelerator_model.py
- accelerator_abstract/models/base_application_question.py
- accelerator_abstract/models/base_judging_form_element.py
- accelerator_abstract/models/base_question.py
**Changes Introduced:**
-  Add help text for choice options
**Testing:**
-  As an Admin: Visit [Question admin](http://localhost:8181/admin/mc/question/49/change/), [Application Question page](http://localhost:8181/admin/mc/applicationquestion/1/change/) and [Judging form element page](http://localhost:8181/admin/mc/judgingformelement/13/change/)
**Expected results:**
- You should be able to view a help text in all the choice options
Help text: 
> Provide a list of options separated by a “|” (ie. Yes|No)
> [AC-6883] Question and Application question admin pages include help text for adding "|"

- Makefile
- Bumps up django version
- Travis build with Django 2.2.10 does not fail
- Follow testing instructions on the [accelerate](https://github.com/masschallenge/accelerate/pull/2480) PR
> [AC-7386] Apply Django security release 2.2.10

- accelerator/tests/test_base_user_role.py
- accelerator_abstract/models/base_startup_role.py
- accelerator_abstract/models/base_user_role.py
**Changes Introduced:**
- add ALUM to base startup role model
**Testing**
- checkout to `AC-7517` in `django-accelerator` and `accelerate`.
- Navigate to any startup preview page with the following roles: [entrant, finalist, winner, or alumni]
Check for: 
- `Entrant` labels are visible to staff only
- All other labels are visible to staff, experts, finalists, and alumni 
- Under the heading Participation, display programs the startup in which the startup is/has been an entrant, finalist, winner, or alumni as list items under the heading
- Labels follow the format `year + status`, for example, **2017 Finalist**
- If `alumni` in `program_name`, finalist tag is not displayed in the same program
- The most recent is displayed first
[sibling …
> [AC-7517] add ALUM to base startup role model

- accelerator/migrations/023_alter_topics_field_office_hours.py
- accelerator_abstract/models/base_mentor_program_office_hour.py
- Remove the character limit on the topics field
- Check out this branch
- Visit the office hours page for Boston 2019 [here](http://localhost:8181/officehours/bos/2019/)
- Schedule office hours
- Try reserving office hours for a finalist.
- Notice that there is a limit of 2000 chars on Meeting information
> AC-7723 Too-long 'topics' field in OfficeHoursReservationView should not throw a 500

- setup.py
This removes the version pin for django sitetree. 
to test:
- Checkout this branch on django accelerator
- ssh into the accelerate container and re-run bin/buildout and confirm it succeeds
> [AC-7987-fix] removing version pin

- accelerator/migrations/0019_add_deferred_user_role.py
**Changes introduced in [AC-7743](https://masschallenge.atlassian.net/browse/AC-7743)**
- Renamed the User role key from user to name.
**How to test**
- The error in migration 0019 (param "user" on line 12 should be "name") is corrected
> [AC-7743]: P1: Fix error in migration 0019

- accelerator/tests/contexts/judge_feedback_context.py
- accelerator_abstract/models/base_judge_application_feedback.py
- Validate judge feedback form
**How to test**
- Checkout to this branch on `accelerate` and `django-accelerator`
- As a staff user, set the following judging rounds as active and in the present:[judging round 69](http://localhost:8181/admin/mc/judginground/69/), [judging round 74](http://localhost:8181/admin/mc/judginground/74/)
- Set [panel](http://localhost:8181/admin/mc/panel/77556/) to ACTIVE.
```
on django shell:
from mc.models import User
u = User.objects.get(email='sdavis@cxoadvisorygroup.com')
u.set_password('yourtestpass'); u.save()
```
- Login as sdavis@cxoadvisorygroup.com
- Go to http://localhost:8181/feedback/386/77556/15258/
- Confirm this ticket meets the definition of done according to [AC-8200](https://masschallenge.atlassian.net/browse/AC-8200)
- …
> [AC-8200] Validate judge feedback form

- requirements/dev.txt
- settings.py
- setup.py
- Update MySQL data type mapper to use `datetime` instead of `datetime(6)`
**Testing**
- ssh into test3
- Confirm that you can run migrations without MySQL compatibility error: `django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax;`
[Sibling PR](https://github.com/masschallenge/accelerate/pull/2833)
> [AC-8419] P0: Django 2.2  DateTime fields are incompatible with MySQL 5.5

- accelerator/migrations/0028_add_gender_choices_object.py
- Removes swappable option in migration 0028
- Drop the database `make db-shell` and in the mysql console `drop database mc_dev;`
- Recreate the database `create database mc_dev;` and exit
- load the database `make load-db` , migration `0028` should be applied
- verify in the database has the changes expected, the table `accelerator_ genderchoices` exists in the database
> [AC-8484] Migration 0028 reintroduces swappable

- accelerator_abstract/models/base_core_profile.py
Changes introduced in [AC-8516](https://masschallenge.atlassian.net/browse/AC-8516)
- P2: Expert profile demographic fields are difficult to use
How to test
- The multi-select fields for ethno-racial identity and gender identity are consistent with the mockup so seven options are visible at once; mockup: https://www.figma.com/file/8zEeyAcxQCFtNf1oQtuAsF/Demographic-Information?node-id=163%3A0
-
> [AC-8516] P2: Expert profile demographic fields are difficult to use 

- accelerator/tests/factories/user_deferrable_modal_factory.py
https://masschallenge.atlassian.net/browse/AC-8673
Fixed a factory which provided a bare datetime. 
See sibling PR on accelerate.
> [AC-8673] Eliminate warning: naive datetime

- accelerator/tests/test_utils.py
- accelerator_abstract/models/base_core_profile.py
https://masschallenge.atlassian.net/browse/AC-8173
Confirm that references to expert_nav feature flag are removed
Note: this should merge with its sibling PR: https://github.com/masschallenge/accelerate/pull/2925
> [AC-8173] Remove expert_nav feature-flagging

- accelerator_abstract/models/base_core_profile.py
Changes introduced in [AC-8373](https://masschallenge.atlassian.net/browse/AC-8373)
- this change makes the gender field in the base_core_profile optional
- this is a pre-requisite for these PRs:
https://github.com/masschallenge/accelerate/pull/2938
https://github.com/masschallenge/django-accelerator/pull/401
How to test:
- You can register as an entrepreneur or expert while checking out https://github.com/masschallenge/accelerate/pull/2938 successfully.
> [AC-8373] make gender field optional

- accelerator/tests/test_core_profile.py
- accelerator_abstract/models/base_core_profile.py
- move functions needed for Startup membership/ownership to CoreProfile
**Testing**
- Confirm that the following def of done conditions are met:
- move is_alum_in_residence and first_startup onto CoreProfile
- make add no-op get_active_alerts to EntrepreneurProfile
- Result of this ticket: EntrepreneurProfile defines no functions
[Sibling PR](https://github.com/masschallenge/accelerate/pull/2959)
> [AC-8802] Ensure that CoreProfile has functions needed for Startup membership/ownership

- accelerator/models/core_profile.py
- accelerator/models/expert_profile.py
- accelerator/tests/test_core_profile.py
**Testing**
- - Visit [aloglia dev_community index](https://www.algolia.com/apps/3WW3PBJ1CW/explorer/browse/dev_community?searchMode=search)
- Confirm that the following conditions are satisfied:
- Create an index for the Community directory
- index on CoreProfile
- index name is “Community”
- index the same fields currently indexed for Mentor and People directories (union of the set)
- prod, staging, and dev indexes (as we currently do for Mentor and People directories)
- Filters will include Industry, Subindustry, Role (Finalist, Alumni, Mentor, Staff), Specialty (Investor, Executive, Lawyer), office hours availability
- New filter: Program participation - user has Finalist or Confirmed Mentor role grant in an active program 
- determine when this index needs to be updated and provide …
> [AC-9028] Create algolia index for community directory

- .travis.yml
This PR updates .travis.yml to use rebase rather than merge as the behavior on pull. It's hoped that this will clean up the inability to create passing PR builds.
> [AC-9294] Update travis config to rebase on pull rather than merge

- accelerator/models/core_profile.py
- accelerator/tests/test_core_profile.py
- add percent_complete function to get profile completion progress in %
**Testing**
- Visit any of the unified profile views e.g https://test-cam.masschallenge.org/profile/ 
- Confirm that the definition of done according to [AC-9340](https://masschallenge.atlassian.net/browse/AC-9340) is satisfied
[Sibling PR](https://github.com/masschallenge/accelerate/pull/3196)
> [AC-9340] Create Personal Profile progress bar

- accelerator/tests/test_core_profile.py
- accelerator/tests/utils.py
- accelerator_abstract/models/base_core_profile.py
https://masschallenge.atlassian.net/browse/AC-9402
To review: on a local machine pointing to a flagsmith environment with feature flag "activate_unified_profile_views" set to true, become an entrepreneur user (on clean db, user 93049 is an example)
when visiting localhost:8181/ you should be redirected to /profile, _not_ to /applicant
> [AC-9402] Default redirect for entrepreneur users should be /profile

- accelerator/models/core_profile.py
- accelerator/tests/test_core_profile.py
- add `program_interest` field as part of the  get profile completion progress computation
**Testing**
- Confirm that the definition of done according to [AC-9535](https://masschallenge.atlassian.net/browse/AC-9635) is satisfied
[Sibling PR](https://github.com/masschallenge/accelerate/pull/3268)
> [AC-9535] Include revised program interest in Personal Profile progress calculation

- accelerator/tests/test_core_profile.py
- accelerator/tests/test_utils.py
- accelerator/utils.py
- setup.py
- use flagsmith from PyPi
**Testing**
- On django-accelerator and accelerate: git checkout to AC-9609,  make build and runserver
- Confirm that flagsmith continues to work as expected
- Confirm that the def of done according to [AC-9609](https://masschallenge.atlassian.net/browse/AC-9609) is satisfied
[Sibling PR](https://github.com/masschallenge/accelerate/pull/3360)
**Notes**
We have pinned flagsmith to version  [2.0.1](https://pypi.org/project/flagsmith/3.0.1/). The latest flagsmith version [3.0.1](https://pypi.org/project/flagsmith/2.0.1/) only supports  Python >=3.7.0, <4. 
[AC-9691](https://masschallenge.atlassian.net/browse/AC-9691) will upgrade flagsmith to the latest version once we upgrade our python version
> [AC-9609] Switch flagsmith source to use PyPi rather than github
