masschallenge/django-accelerator

.travis.yml
Makefile
accelerator/models/__init__.py
accelerator/test_runner.py

To test:
- Check Travis log for an error that starts with: "/bin/sh: 1: ["

AC-4819-make-fix: Proposed fix for make issue reported in AC-4819

---

accelerator/tests/factories/__init__.py

**Test:**
- see that importing `from accelerator.tests.factories import OrganizationFactory` works.

[AC-4885] - add OrganizationFactory to init file

---

Makefile

[AC-4936] Add dependencies for coverage target

---

accelerator_abstract/models/accelerator_model.py

This has been deployed hot-patch-style in staging and production and checked by Jeff.

[AC-5478a] fixed circularity by calling str on id instead of object

---

accelerator/migrations/0004_fix_acstream_contenttypes.py

**Changes introduced:**
- fix codestyle issues.
- select old content type by specifically filtering app label.
- add missing content types for panel, program, paypalrefund and baseprofile
- DRY the actor/object/target aspect of this change.

[AC-5566-fix] - FOR SHANKAR - suggested fixes for PR

---

accelerator/tests/test_core_profile.py
accelerator_abstract/models/base_base_profile.py
accelerator_abstract/models/base_core_profile.py
simpleuser/models.py

**Changes Introduced in [AC-5323](https://masschallenge.atlassian.net/browse/AC-5323):**
- See PR on Accelerate: https://github.com/masschallenge/accelerate/pull/1806

[AC-5323] - Improve performance of PanelStatsView

---

accelerator/tests/contexts/__init__.py
accelerator/tests/contexts/analyze_judging_context.py
accelerator/tests/contexts/judge_feedback_context.py
accelerator/tests/factories/judge_application_feedback_factory.py

Need for the PR https://github.com/masschallenge/impact-api/pull/176
See that PR for testing instructions.

[AC-5625] Context and tweaks to support impact-api tests for AnalyzeJudgingRound

---

accelerator/tests/contexts/judge_feedback_context.py

THIS SHOULD GET MERGED BEFORE https://github.com/masschallenge/impact-api/pull/180

AC-5700: Add is_active flag to JudgeFeedbackContext

---

accelerator/tests/contexts/analyze_judging_context.py
accelerator/tests/contexts/judge_feedback_context.py

See https://github.com/masschallenge/impact-api/pull/185 for details.

Ac 5703: Implement the dynamic matrix algorithm

---

accelerator/tests/contexts/analyze_judging_context.py
accelerator/tests/contexts/judge_feedback_context.py

This PR improves contexts to allow some tests on AC-5900 to be written with less fuss and bother.

[AC-5900] Update contexts

---

simpleuser/models.py

See [accelerate PR](https://github.com/masschallenge/accelerate/pull/1946) for testing instructions.

[AC-6121] add uniqueness constraint to email field

---

simpleuser/tests/factories/user_factory.py

**[Main PR is in accelerate](https://github.com/masschallenge/accelerate/pull/1959)**. The change here is minor, just changing the `UserFactory`'s dummy password to pass validation.

AC-6153 - validate passwords

---

accelerator/tests/contexts/__init__.py
accelerator/tests/contexts/startup_team_member_context.py

- moved startup team member context here from accelerate
- Centralized context on the [sibling PR](https://github.com/masschallenge/accelerate/pull/2056)

AC-6375: Rebuild person profile page using front-end directory repo

---

accelerator/tests/contexts/analyze_judging_context.py

a small change to support a test in [this pr](https://github.com/masschallenge/impact-api/pull/269)

[AC-6483] Allow bypass of add_application in AnalyzeJudgingContext

---

accelerator/migrations/0051_add_register_for_events_to_event_subnav_items.py
accelerator/sitetree_navigation/sub_navigation/event_subnav_definition.py

- Remove unnecessary imports.
- Remove duplicated logic
- checkout this branch and `make load-remote-db` to get a clean DB
- Navigate to [link](http://localhost:8181/admin/mc/navtree/3/change/)
- You should see the new `Register for events` nav tree item

AC-6667 Cleanup AC-6521 Migration (0051)

---

.travis.yml

A test commit to test an AC-6810 egde case

[AC-6810-pr] pr to pr commit

---

accelerator/migrations/0076_change_description_to_textfield.py

Changes introduced Fix migration conflict brought by AC-5845

[AC-5845] fix migration conflict

---

accelerator_abstract/models/base_core_profile.py

See https://masschallenge.atlassian.net/browse/AC-7263 for details
To test: load a recent copy of prod db. Sign in as stephanieconnaughton@gmail.com and go to http://localhost:8181/
On development:  error
On branch: redirect to http://localhost:8181/dashboard/bos-mentor-dashboard/dashboard-home/

[AC-7263] Fix redirect issue from AC-7128

---

accelerator/tests/contexts/__init__.py
accelerator/tests/contexts/criterion_option_spec_context.py
accelerator/tests/contexts/judge_feedback_context.py
accelerator/tests/contexts/judging_round_context.py
accelerator/tests/factories/judging_round_factory.py

See sibling PR for testing notes

[AC-7310] Validate Judging Form when Judging Round is Made Active

---

accelerator/tests/contexts/analyze_judging_context.py
accelerator/tests/factories/startup_team_member_factory.py

See associated PR for instructions:
masschallenge/accelerate#2635

AC-7833, AC-7833 and AC-7834: Fix impact Api tests and get them to run as part of accelerate test suite

---

setup.py

Also see [impact-api PR](https://github.com/masschallenge/impact-api/pull/454) and [accelerate PR](https://github.com/masschallenge/accelerate/pull/2666)

 AC-7804: Resolve deprecation warnings in New Monolith

---

setup.py

[AC-7987] bumped django-sitetree to 1.15.1

---

Makefile

See [accelerate PR](https://github.com/masschallenge/accelerate/pull/2681) for full context.

AC-7835 - Improve/replace the semantic-release tooling

---

accelerator/tests/factories/factory_utils.py

- Fix expert profile form validation issues
**Testing**
- Confirm that all the failing tests on AC-8364, AC-8365, and AC-8376 are passing on your local environment/Travis
[Sibling PR](https://github.com/masschallenge/accelerate/pull/2853)

[AC-8485] Fix expert profile form problems affecting AC-8364, AC-8365, AC-8376

---

accelerator_abstract/models/base_core_profile.py

Follow the testing instruction on the accelerate PR

AC-8365 Add demographic fields to Entrepreneur profile

---

accelerator/tests/factories/deferrable_modal_factory.py

**Changes Introduced**
- fix spelling mistake
**Testing**
- check out this branch on `accelerate` and `django-accelerator`
- Confirm that the def of done according to [AC-8418](https://masschallenge.atlassian.net/browse/AC-8418) is satisfied
[Sibling PR](https://github.com/masschallenge/accelerate/pull/2909)

[AC-8418] Add DeferrableModalMiddleware

---

simpleuser/models.py

https://masschallenge.atlassian.net/browse/AC-8836
- verify newly created user has last_login of "None"

[AC-8836] Do not set last_login on user creation

---

accelerator/models/core_profile.py
accelerator/tests/test_core_profile.py

**Change introduced**
- specify pre-filtered results for Community Directory and add access control for CommunityProfilePageView
**Testing**
- URLs: `http://localhost:8181/community/` and `http://localhost:8181/community/<user_id>/`
- Confirm that the definition of done according to [AC-9119](https://masschallenge.atlassian.net/browse/AC-9119) is satisfied
Deployed to https://test-ian.masschallenge.org/
[Sibling PR](https://github.com/masschallenge/accelerate/pull/3070)

[AC-9119] Specify pre-filtered results for Community Directory

---

accelerator/tests/factories/__init__.py
accelerator/tests/factories/partner_application_interest_factory.py

https://masschallenge.atlassian.net/browse/AC-9168
Verify that factory is added for model

[AC-9168] add factory for model

---

accelerator/tests/factories/__init__.py

Verify that the changes made meet the def of done in https://masschallenge.atlassian.net/browse/AC-9198
[JIRA LINK](https://masschallenge.atlassian.net/browse/AC-9198)

[AC-9198] adds PartnerJudgingRoundChallengeFactory imports

---

accelerator/tests/factories/core_profile_model_factory.py
accelerator_abstract/models/__init__.py
accelerator_abstract/models/base_core_profile.py

https://masschallenge.atlassian.net/browse/AC-9525
minor cleanup encountered while fixing bug

[AC-9525] convert literals to constants for importing

---

accelerator/migrations/0110_remove_bucket_list_program_role_20220707_1001.py

[AC-9556](https://masschallenge.atlassian.net/browse/AC-9556)
**How to test:**
- Ensure the definition of done on [AC-9556](https://masschallenge.atlassian.net/browse/AC-9556)
are all met.
Sibling PR: https://github.com/masschallenge/accelerate/pull/3340

[AC-9556]: Delete code and data supporting "Bucket List" reports
